"""empty message

Revision ID: b47b34e94f98
Revises:
Create Date: 2025-03-25 23:13:50.783776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "b47b34e94f98"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shortenedurl",
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("main_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("short_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("expired", sa.Boolean(), nullable=False),
        sa.Column("visits", sa.Integer(), nullable=False),
        sa.Column("last_usage", sa.Float(), nullable=True),
        sa.Column("expires_at", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_shortenedurl_short_url"), "shortenedurl", ["short_url"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_shortenedurl_short_url"), table_name="shortenedurl")
    op.drop_table("shortenedurl")
    # ### end Alembic commands ###
